version: '2.0'
# version: '3.1'

services:

  mysqlyumfood:
    image: mysql:5.7
    environment: 
      MYSQL_USER: 'yumfood'
      MYSQL_PASSWORD: 'yumfood'
      MYSQL_ROOT_PASSWORD: 'yumfood'
      MYSQL_DATABASE: 'yumfood'
    ports: 
      - 3309:3306

  java:
    build: .
    restart: on-failure
    depends_on: 
      - mysqlyumfood
    ports: 
      - 8080:8080
    environment: 
      WAIT_HOSTS: mysqlyumfood:3306
      WAIT_HOSTS_TIMEOUT: 120
      MYSQL_DATABASE_HOST: mysqlyumfood
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE_NAME: yumfood
